export default [
  {
    name: "Grigor",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-UTLKX2TGA-ea276a5bba16-512",
    animals: ["alpaca", "hedgehog", "octopus", "zebra", "wolf"],
  },
  {
    name: "Mojgan",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-ULZJ940N6-f8e2f84ad17f-512",
    animals: ["sloth", "otter", "turtle", "puppy", "zebra"],
  },
  {
    name: "Niglio",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-U012QV9H99R-g785f072b58d-512",
    animals: ["octopus", "koala", "donkey", "zebra", "canary"],
  },
  {
    name: "Ahmad_A",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-UTZDPCH5E-760feb35b8b6-512",
    animals: ["wolf", "fox", "monkey", "iguana", "baboon"],
  },
  {
    name: "Reda",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-UMD63SAT0-dae012d21564-512",
    animals: ["whale", "lemur", "wolf", "sloth", "turtle"],
  },
  {
    name: "Shauna",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-UPRAK6N3A-cbe808792cfd-512",
    animals: ["koala", "canary", "wolf", "fox", "rabbit"],
  },
  {
    name: "Carolyn",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-U6V2ZP0LT-367b2022dc47-512",
    animals: ["koala", "elk", "alpaca", "whale", "donkey"],
  },
  {
    name: "Eric",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-U52QJ8UN5-641016255a5f-512",
    animals: ["whale", "rabbit", "panda", "zebra", "canary"],
  },
  {
    name: "James",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-UJX15DJBU-83cbd9f520da-512",
    animals: ["wolf", "alpaca", "lemur", "jaguar", "hedgehog"],
  },
  {
    name: "Halil",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-UM4L42L0Z-da5edcd1d616-512",
    animals: ["donkey", "puppy", "turtle", "baboon", "iguana"],
  },
  {
    name: "Anna",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-UMD63EK9U-c54a7018f187-512",
    animals: ["whale", "rabbit", "fox", "baboon", "koala"],
  },
  {
    name: "Osiname",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-U018DG77HL1-afe0d59dfd30-512",
    animals: ["otter", "panda", "iguana", "zebra", "koala"],
  },
  {
    name: "Monica",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-UTLKXNKFU-5b75505cb8f1-512",
    animals: ["alpaca", "jaguar", "turtle", "donkey", "lemur"],
  },
  {
    name: "Emre",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-UT8F6J11S-3ab5c1cd2129-512",
    animals: ["fox", "wolf", "otter", "elk", "donkey"],
  },
  {
    name: "Wissem",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-U01763F19QF-08a77a3588bf-512",
    animals: ["panda", "monkey", "donkey", "elk", "fox"],
  },
  {
    name: "Ahmad_K",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-UMB1P8RB2-bbd6d181ee79-512",
    animals: ["turtle", "alpaca", "iguana", "yak", "hedgehog"],
  },
  {
    name: "Anıl",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-UM71DC31A-fb053fa54159-512",
    animals: ["whale", "octopus", "sloth", "yak", "hedgehog"],
  },
  {
    name: "Sara",
    role: "teacher",
    image: "https://ca.slack-edge.com/T0HN7F83D-U016WALJ2EM-g27ccbcad20a-512",
    animals: ["wolf", "alpaca", "rabbit", "panda", "octopus"],
  },
  {
    name: "Tarik",
    role: "student",
    image: "https://ca.slack-edge.com/T0HN7F83D-U979P74TS-8a68bb8eefe0-512",
    animals: ["lemur", "turtle", "puppy", "zebra", "octopus"],
  },
];
